### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404:

### ISSUE THREAD

**Issue by Feaxure-fresh** [Project-Splinter/MonoPort#13]
![87f1e0fcb530eb5d7ba307b3c197570](https://user-images.githubusercontent.com/69803979/97081330-4ebc3600-1634-11eb-8b45-2e5e10d6c543.png)

Environments:  Windows 10
How can I solve this problem?
When I tried to open this url : https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pt in my web, I got following returns in that page:
{"requestStatus":{"statusCode":"NOT_FOUND","statusDescription":"Model not found","requestId":"11c72acd-0d81-4dc4-88cd-7e327a3f9d50"}}

**Comment by YuliangXiu** [comment]
This old model does not exist anymore, so please change the code in ``/Users/[Username]/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/hubconf.py``
 from [original version](https://github.com/NVIDIA/DeepLearningExamples/blob/torchhub/hubconf.py#L367) 
```python
if pretrained:
        if fp16:
            checkpoint = 'https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp16/versions/1/files/nvidia_ssdpyt_fp16_20190225.pt'
        else:
            checkpoint = 'https://api.ngc.nvidia.com/v2/models/nvidia/ssdpyt_fp32/versions/1/files/nvidia_ssdpyt_fp32_20190225.pt'
```
to
```python
if pretrained:
        if fp16:
            checkpoint = 'https://api.ngc.nvidia.com/v2/models/nvidia/ssd_pyt_ckpt_amp/versions/19.09.0/files/nvidia_ssdpyt_fp16_190826.pt'
        else:
            checkpoint = 'https://api.ngc.nvidia.com/v2/models/nvidia/ssd_pyt_ckpt_amp/versions/20.06.0/files/nvidia_ssdpyt_amp_200703.pt' # AMP
        

```

**Comment by YuliangXiu** [comment]
#26
