### ISSUE TITLE
freeglut (foo): failed to open display ''

### ISSUE THREAD

**Issue by jiandandian2** [Project-Splinter/MonoPort#14]
I run it on the Google Colab, and I get this problem, do u know how to solve it? thank u
<img width="1598" alt="屏幕快照 2020-11-02 下午4 12 30" src="https://user-images.githubusercontent.com/33227739/97844698-6e371b00-1d26-11eb-87e6-b1ec82418ef0.png">

**Comment by jiandandian2** [comment]
i also run it in the vnc sever, and it gets mistakes like this

<img width="1003" alt="屏幕快照 2020-11-03 下午2 52 23" src="https://user-images.githubusercontent.com/33227739/97956783-88373300-1de4-11eb-871b-92f273e83197.png">

how to solve it? i'll be grateful

**Comment by Adorablepet** [comment]
@YuliangXiu I have such a problem. How to solve it? Thanks.
