### ISSUE TITLE
Errors When Trying To Run & Questions

### ISSUE THREAD

**Issue by ftaker887** [Project-Splinter/MonoPort#2]
Really interesting project, thanks for sharing! There are a few things that prevent this from running correctly. Currently running on Arch.

- The monoport folder should be in the RTL folder, not the root directory.

- requirements.txt doesn't have the specified torch and torchvision requirements. Please update it so that inconsistencies are solved.

- I keep getting out of memory errors when trying to run this on an image sequence or video. I have 8GB of vram on my GPU.

Now for the questions. Does the full body need to be showing for inference to work properly? If so, any plans to change this? For example, only the chest, shoulders, and head showing in video.

How do we export the meshes into a separate file? Is this possible currently?

Thanks!

**Comment by YuliangXiu** [comment]
- the command is `python RTL/main.py`, thus there is no need to place the monoport folder under RTL folder
- thanks for reminding, I have updated the `requirements.txt`, and you can also install torch related package with `conda install pytorch==1.4.0 torchvision cudatoolkit=10.1 -c pytorch` (please refer to https://pytorch.org/get-started/locally/)
- you need at least 2 GPUs to run our demo, the memory usage will be around 5GB in GPU1 and 10GB in GPU2
- YES. Our method is designed for full body inference, even though it works sometimes on partial human. In the near future, we do not have any plan to support this feature, but this is really a valuable research topic to explore
- You can refer to [utils.py](https://github.com/Project-Splinter/ImplicitSegCUDA/blob/d2b283b113ec04f8a48a534b08d80f56e1d62183/implicit_seg/functional/utils.py#L39) to generate meshes with the help of marching cube algorithm

**Comment by ftaker887** [comment]
>     * the command is `python RTL/main.py`, thus there is no need to place the monoport folder under RTL folder
> 
>     * thanks for reminding, I have updated the `requirements.txt`, and you can also install torch related package with `conda install pytorch==1.4.0 torchvision cudatoolkit=10.1 -c pytorch` (please refer to https://pytorch.org/get-started/locally/)
> 
>     * you need at least 2 GPUs to run our demo, the memory usage will be around 3.4G in GPU1 and 9.7GB in GPU2
> 
>     * YES. Our method is designed for full body inference, even though it works sometimes on partial human. In the near future, we do not have any plan to support this feature, but this is really a valuable research topic to explore
> 
>     * You can refer to [utils.py](https://github.com/Project-Splinter/ImplicitSegCUDA/blob/d2b283b113ec04f8a48a534b08d80f56e1d62183/implicit_seg/functional/utils.py#L39) to generate meshes with the help of marching cube algorithm

Okay I see. Thanks for responding!

**Comment by YuliangXiu** [comment]
#10
