### ISSUE TITLE
'freeglut (foo): failed to open display ''

### ISSUE THREAD

**Issue by Adorablepet** [Project-Splinter/MonoPort#21]
Thanks for you  sharing codes. I have a question about running. When appearing error, about `freeglut (foo): failed to open display`. Could you tell how to solve it? Thanks again.
my environment as follows:
```
ubuntu 18.04 without desktop, with server version
I have installed vncserver, xfce4, but still appeared this error
```

**Comment by dannychen099** [comment]
Same issue when I try to run it on Google Colab

**Comment by shawkontzu** [comment]
@Adorablepet This is due to running openGL on headless device. By default opengl requires X11 server, but you can run headless opengl using EGL

https://developer.nvidia.com/blog/linking-opengl-server-side-rendering/
https://developer.nvidia.com/blog/egl-eye-opengl-visualization-without-x-server/
