### ISSUE TITLE
Not Able to find runnable version including ‘CBN’、‘HRNet‘ and ’one-hot encode for z' which is refered in the paper.

### ISSUE THREAD

**Issue by YrralH** [Project-Splinter/MonoPort#22]

**Comment by YrralH** [comment]
I wondered if they are included and if they really work better.

**Comment by YuliangXiu** [comment]
[one-hot emcode](https://github.com/Project-Splinter/MonoPort/blob/master/monoport/lib/modeling/normalizers/DepthNormalizer.py)
[CBN](https://github.com/autonomousvision/occupancy_networks/blob/ddb2908f96de9c0c5a30c093f2a701878ffc1f4a/im2mesh/onet/models/decoder.py)
[HRNet](https://github.com/Project-Splinter/MonoPort/blob/master/monoport/lib/modeling/backbones/HRNetFilters.py)
