### ISSUE TITLE
Not able to run the demo

### ISSUE THREAD

**Issue by Pbb-land** [Project-Splinter/MonoPort#23]
Hello, I tried to run the demo with two TITAN xp GPUs(12G per GPU),but always failed when initial the human segmentation model. Here's my log.

loading networkG from ./data/PIFu/net_G ...
loading networkC from ./data/PIFu/net_C ...
initialize data streamer ...
[ WARN:0] global /tmp/pip-req-build-7m_g9lbm/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
Using cache found in /home/pbb/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
Using cache found in /home/pbb/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
Traceback (most recent call last):
  File "RTL/main.py", line 155, in <module>
    device=cuda_backbone_G, verbose=False)
  File "/disk4/pbb/opensource/human_inst_seg/human_inst_seg/unet.py", line 63, in __init__
    self.det_engine = Detection(device=device)
  File "/home/pbb/.local/lib/python3.7/site-packages/human_det/ssd.py", line 22, in __init__
    model_math='fp16' if self.fp16 else 'fp32'
  File "/disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/hub.py", line 366, in load
    model = entry(*args, **kwargs)
  File "/home/pbb/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/hubconf.py", line 369, in nvidia_ssd
    ckpt = torch.load(ckpt_file)
  File "/disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 85292 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fb0f45c8193 in /disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x18cd59f (0x7fb0344da59f in /disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7fb034ca2ba7 in /disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x939a17 (0x7fb0c65f8a17 in /disk4/pbb/anaconda3/envs/MonoPort/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: __libc_start_main + 0xe7 (0x7fb102f17bf7 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by YuliangXiu** [comment]
#13
