### ISSUE TITLE
RUNING ERRORS    (core dumped)

### ISSUE THREAD

**Issue by lunacy-xc** [Project-Splinter/MonoPort#5]
ubuntu 16.04
python 3.7
torch 1.4
It keeps downloading everytime 
"https://github.com/NVIDIA/DeepLearningExamples/archive/torchhub.zip" to /home/asus/.cache/torch/hub/torchhub.zip
And finally occurs the error : sus/anaconda3/envs/mo/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.soAborted (core dumped)

**Comment by YuliangXiu** [comment]
Do you try to download this package manually and put this zipfile under target folder?

**Comment by lunacy-xc** [comment]
> Do you try to download this package manually and put this zip file under target folder?

Yes ,  but the file will be automatically deleted and re-download the zip file again

**Comment by lunacy-xc** [comment]
> Do you try to download this package manually and put this zipfile under target folder?

I have solved this problem by updating  my ubuntu from  16.04 to 18.04 and It can run now
