### ISSUE TITLE
i get this demo problem

### ISSUE THREAD

**Issue by jiandandian2** [Project-Splinter/MonoPort#8]
![image](https://user-images.githubusercontent.com/33227739/91511249-dece4f80-e911-11ea-89cc-ab5073af1f50.png)

**Comment by YuliangXiu** [comment]
It looks like that you did not download the pretrained model of human_det successfully. You can try to reinstall the human_det and human_inst_seg and see what happens.

**Comment by YuliangXiu** [comment]
#13
